
- name: Install dependencies for NWA_alert
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - python3-apt
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python3-setuptools
  become: yes
  when: apt.changed

- name: Clone project branch {{ PROJECT_VERSION }} from github
  git:
    repo: "{{ PROJECT_REPOSITORY }}"
    dest: "{{ PROJECT_PATH }}"
    force: yes
    version: "{{ PROJECT_VERSION }}"
    accept_hostkey: yes
    # key_file: /root/.ssh/id_rsa
  become: yes
  register: project

- name: Pip install -r requirements.txt
  pip:
    chdir: "{{ PROJECT_PATH }}"
    requirements: requirements.txt
    state: latest
    virtualenv: venv
    virtualenv_command: virtualenv
  become: yes
  when: project.changed

- name: Copy in .env file
  template:
    src: env.j2
    dest: "{{ PROJECT_PATH }}/.env"
  become: yes
  when: project.changed

