# Common tasks


- name: Set timezone to Europe/Oslo
  ansible.builtin.timezone:
    name: Europe/Oslo
  become: yes

- name: Enable firewall
  ansible.builtin.ufw:
    state: enabled
  become: yes
  register: ufw

- name: Open SSH and close all other ports
  ansible.builtin.ufw:
    rule: allow
    name: OpenSSH
    policy: deny
  become: yes
  when: ufw.changed

- name: Throttle brute force SSH login attepmpts
  ansible.builtin.ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: yes
  when: ufw.changed

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    name: "*"
    update_cache: yes
    cache_valid_time: yes
    state: latest
  become: yes
  register: apt

- name: Maintenance Montly server reboot
  ansible.builtin.cron:
    name: "Monthly server reboot"
    minute: "30"
    hour: "1"
    day: "1"
    user: root
    job: "sudo reboot now 'CRON Monthly maintenance reboot in progress'"
  become: yes