- name: install tibber systemd unit file
  template:
    src: tibber.j2
    dest: /etc/systemd/system/tibber.service
  become: yes

- name: start tibber
  systemd:
    daemon_reload: yes
    state: restarted
    name: tibber
  become: yes
