- name: install tibber systemd unit file
  template:
    src: tibber.j2
    dest: /etc/systemd/system/tibber.service
  become: yes

- name: start tibber
  systemd:
    enabled: yes
    daemon_reload: yes
    state: restarted
    name: tibber
  become: yes

# @TODO job fails when pulling data from Tibber API around midnight ocassionally, this is a workaround.
- name: Ensure job restarted daily
  ansible.builtin.cron:
    name: "Tibber restarted daily"
    minute: "1"
    hour: "1"
    user: root
    job: "sudo systemctl restart tibber"
  become: yes

